
services:
  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
      - "8090:8080"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/bitnami


  spark-master:
    image: bitnami/spark
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_WORKER_CORES: 2
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT_NUMBER: 7077
      SPARK_MASTER_WEBUI_PORT_NUMBER: 8080

  spark-worker:
    image: bitnami/spark
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT_NUMBER: 7077
      SPARK_WORKER_PORT_NUMBER: 8081
      SPARK_WORKER_WEBUI_PORT_NUMBER: 8081
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT_NUMBER: 7077
      SPARK_WORKER_PORT_NUMBER: 8082
      SPARK_WORKER_WEBUI_PORT_NUMBER: 8082
    depends_on:
      - spark-master


volumes:
  kafka-data:
  spark-data:
