
services:
  spark:
    image: bitnami/spark
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_WORKER_CORES: 2
    networks:
      - internal

  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   restart: always
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: yes
  #   networks:
  #     - internal

  # kafka:
  #   image: bitnami/kafka:latest
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
  #     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
  #     KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
  #     ALLOW_PLAINTEXT_LISTENER: yes
  #   depends_on:
  #     - zookeeper
  #   # volumes:
  #   #   - kafka-data:/bitnami
  #   networks:
  #     - internal



volumes:
  kafka-data:
  spark-data:

networks:
  internal:
    driver: bridge
